VERSION="2.0.0"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
SIGNING_KEY="GD26YD5HBCFWLUJBQLHAFPNO442QQZNAYMMPRD4NWVOOIZ3Y3AH3IFWF"
ACCOUNTS=["GD26YD5HBCFWLUJBQLHAFPNO442QQZNAYMMPRD4NWVOOIZ3Y3AH3IFWF"]
WEB_AUTH_ENDPOINT="https://sep10-server-production.up.railway.app/auth"
TRANSFER_SERVER_SEP0024="https://mgaccess.moneygram.com"

[DOCUMENTATION]
ORG_NAME="Testnet Wallet"
ORG_URL="https://somt-oss.github.io/stellar-toml2"
ORG_OFFICIAL_EMAIL="somto@tender.cash"
