ACCOUNTS=["GD26YD5HBCFWLUJBQLHAFPNO442QQZNAYMMPRD4NWVOOIZ3Y3AH3IFWF"]
SIGNING_KEY="GD26YD5HBCFWLUJBQLHAFPNO442QQZNAYMMPRD4NWVOOIZ3Y3AH3IFWF"
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Testnet Wallet"
